<?php
session_start();
$D1_DATE = date("d/m",$_SESSION['D1_TS_Start']);
$D2_DATE = date("d/m",$_SESSION['D2_TS_Start']);
$D3_DATE = date("d/m",$_SESSION['D3_TS_Start']);
$D4_DATE = date("d/m",$_SESSION['D4_TS_Start']);
$D5_DATE = date("d/m",$_SESSION['D5_TS_Start']);

$D1_Start = date('H:i', $_SESSION['D1_TS_Start']);
$D2_Start = date('H:i', $_SESSION['D2_TS_Start']);
$D3_Start = date('H:i', $_SESSION['D3_TS_Start']);
$D4_Start = date('H:i', $_SESSION['D4_TS_Start']);
$D5_Start = date('H:i', $_SESSION['D5_TS_Start']);

$D1_End = date('H:i', $_SESSION['D1_TS_End']);
$D2_End = date('H:i', $_SESSION['D2_TS_End']);
$D3_End = date('H:i', $_SESSION['D3_TS_End']);
$D4_End = date('H:i', $_SESSION['D4_TS_End']);
$D5_End = date('H:i', $_SESSION['D5_TS_End']);

require('fpdf.php');

class PDF extends FPDF
{
// Page header
function Header()
{
  global $D1_DATE;
  global $D5_DATE;
    // Logo
    $this->Image('logo.png',10,6,30);
    // Arial bold 15
    $this->SetFont('Arial','B',15);
    // Move to the right
    $this->Cell(40);
    // Title
    $this->Cell(100,10,'Hours From ' . $D1_DATE . ' - ' . $D5_DATE ,0,0,'C');
    // Line break
    $this->Ln(20);
}

// Page footer
function Footer()
{
    // Position at 1.5 cm from bottom
    $this->SetY(-15);
    // Arial italic 8
    $this->SetFont('Arial','I',8);

    $this->Cell(100,10,'Generated by Trogy.NZ Hours Calculator | github.com/trogy/Hours-Calculator' ,0,0,'C');
}
}

// Instanciation of inherited class
$pdf = new PDF();
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetFont('Times','',12);
$pdf->Cell(20);
$pdf->Cell(20,5,'Date',1);
$pdf->Cell(40,5,'Start Time',1);
$pdf->Cell(40,5,'Finish Time',1);
$pdf->Cell(40,5,'Day Total',1);
$pdf->Ln(10);
$pdf->Cell(20);
$pdf->Cell(20,10,$D1_DATE,1);
$pdf->Cell(40,10,$D1_Start,1);
$pdf->Cell(40,10,$D1_End,1);
$pdf->Cell(40,10,$_SESSION['D1_TOTAL'],1);
$pdf->Ln(10);
$pdf->Cell(20);
$pdf->Cell(20,10,$D2_DATE,1);
$pdf->Cell(40,10,$D2_Start,1);
$pdf->Cell(40,10,$D2_End,1);
$pdf->Cell(40,10,$_SESSION['D2_TOTAL'],1);
$pdf->Ln(10);
$pdf->Cell(20);
$pdf->Cell(20,10,$D3_DATE,1);
$pdf->Cell(40,10,$D3_Start,1);
$pdf->Cell(40,10,$D3_End,1);
$pdf->Cell(40,10,$_SESSION['D3_TOTAL'],1);
$pdf->Ln(10);
$pdf->Cell(20);
$pdf->Cell(20,10,$D4_DATE,1);
$pdf->Cell(40,10,$D4_Start,1);
$pdf->Cell(40,10,$D4_End,1);
$pdf->Cell(40,10,$_SESSION['D4_TOTAL'],1);
$pdf->Ln(10);
$pdf->Cell(20);
$pdf->Cell(20,10,$D5_DATE,1);
$pdf->Cell(40,10,$D5_Start,1);
$pdf->Cell(40,10,$D5_End,1);
$pdf->Cell(40,10,$_SESSION['D5_TOTAL'],1);
$pdf->Ln(10);
$pdf->Cell(20);
$pdf->Cell(60,10,'Week Total: ' . $_SESSION['TOTAL_HOURS'],1);
$pdf->Output('D','Hours ' . $D1_DATE . ' - ' . $D5_DATE . '.pdf');

?>
