<?php
session_start();
require_once 'key.php';
require_once 'SendGrid/sendgrid-php.php';

$D1_DATE = date("d/m",$_SESSION['D1_TS_Start']);
$D2_DATE = date("d/m",$_SESSION['D2_TS_Start']);
$D3_DATE = date("d/m",$_SESSION['D3_TS_Start']);
$D4_DATE = date("d/m",$_SESSION['D4_TS_Start']);
$D5_DATE = date("d/m",$_SESSION['D5_TS_Start']);

$D1_Start = date('H:i', $_SESSION['D1_TS_Start']);
$D2_Start = date('H:i', $_SESSION['D2_TS_Start']);
$D3_Start = date('H:i', $_SESSION['D3_TS_Start']);
$D4_Start = date('H:i', $_SESSION['D4_TS_Start']);
$D5_Start = date('H:i', $_SESSION['D5_TS_Start']);

$D1_End = date('H:i', $_SESSION['D1_TS_End']);
$D2_End = date('H:i', $_SESSION['D2_TS_End']);
$D3_End = date('H:i', $_SESSION['D3_TS_End']);
$D4_End = date('H:i', $_SESSION['D4_TS_End']);
$D5_End = date('H:i', $_SESSION['D5_TS_End']);

$email = new \SendGrid\Mail\Mail();
$email->setFrom($_SESSION['SG_EMAIL'], $_SESSION['NAME']);
$email->setSubject($_SESSION['NAME'] . " - Hours From: " . $D1_DATE . " - " . $D2_DATE);
$email->addTo($_SESSION['REC_EMAIL'], $_SESSION['REC_NAME']);
$email->setReplyTo($_SESSION['EMAIL'], $_SESSION['NAME']);
$email->addContent("text/plain", "This Email Must Be Viewed In A HTML Compatible Email Client.");
$email->addContent(
    "text/html", "
    <h3> Hello " . $_SESSION['REC_NAME'] . " These are the hours for " . $_SESSION['NAME'] . " at " . $_SESSION['CO_NAME'] . "</h3>
<h2>Hours From: " . $D1_DATE . " - " . $D5_DATE . "</h2>
<hr>
<h4>
" . $D1_DATE . " | " . $D1_Start . " - " . $D1_End . " | " . $_SESSION['D1_TOTAL'] . "<br>
" . $D2_DATE . " | " . $D1_Start . " - " . $D1_End . " | " . $_SESSION['D2_TOTAL'] . "<br>
" . $D3_DATE . " | " . $D1_Start . " - " . $D1_End . " | " . $_SESSION['D3_TOTAL'] . "<br>
" . $D4_DATE . " | " . $D1_Start . " - " . $D1_End . " | " . $_SESSION['D4_TOTAL'] . "<br>
" . $D5_DATE . " | " . $D1_Start . " - " . $D1_End . " | " . $_SESSION['D5_TOTAL'] . "</h4>
<hr>
<h4>WEEK TOTAL:00 Hours 00 Minutes </h4>
<p>Generated by Trogy.NZ Hours Calculator | <a href='https://github.com/trogy/Hours-Calculator'> Github </a><br>
<img src='https://trogy.nz/wp-content/uploads/2021/03/Trogy.NZDARK.png' width='250';> </img> "
);
$sendgrid = new \SendGrid($SG_API_KEY);
try {
    $response = $sendgrid->send($email);
    header('location: sent.php');
    print $response->statusCode() . "\n";
    print_r($response->headers());
    print $response->body() . "\n";
} catch (Exception $e) {
    echo 'Caught exception: '. $e->getMessage() ."\n";
}
